### ISSUE TITLE
UML Diagram

### ISSUE THREAD

**Issue by njl3087** [NotoriousRebel/CSEC380Project#3]
The output of this step should include at minimum Use Cases (and diagrams), Network Topology, Flow Graph(s), Database Schema(s), and State-diagram(s) for each part of the application (This may be done using tools like Visio or online tools like Draw.io). This will require you to understand, review, and consider the requirements for the subsequent activities. You are also required to prepare a site mockup. This may be done in a graphics tool like Photoshop or an online design tool like Invisionapp (https://www.invisionapp.com/)

**Comment by ghost** [comment]
### Network Topology Diagram
![network_topology](https://user-images.githubusercontent.com/33186556/65325143-95bc3a00-db9d-11e9-8109-9a7c6bcb3dcf.png)

**Comment by ghost** [comment]
### End User Interaction Flowchart
![end_user_interaction_flowchart](https://user-images.githubusercontent.com/33186556/65161571-5075fc00-da27-11e9-9fdb-1fa8e5b537f7.png)
